module.exports = [
    { name: 'Basic' },
    { name: 'Legendary' },
    { name: 'Snow' },
    { name: 'World' },
    { name: 'Artifact' },
    { name: 'Battle' },
    { name: 'Conspiracy' },
    { name: 'Creature' },
    { name: 'Dungeon' },
    { name: 'Enchantment' },
    { name: 'Instant' },
    { name: 'Land' },
    { name: 'Phenomenon' },
    { name: 'Plane' },
    { name: 'Planeswalker' },
    { name: 'Scheme' },
    { name: 'Sorcery' },
    { name: 'Tribal' },
    { name: 'Vanguard' }
]